import { DifficultyT } from "@/types/types";

type Riddle = {
  id: number;
  displayOrder: number;
  difficulty: DifficultyT;
  question: string;
  answer: string;
  hint: string | null;
  image?: string;
};

// Additional 200 riddles to expand your collection
export const newRiddles: Riddle[] = [
  // EASY RIDDLES (102-140)
  {
    id: 102,
    displayOrder: 102,
    difficulty: "easy",
    question: "What has one eye but cannot see?",
    answer: "A needle",
    hint: "Used in sewing.",
  },
  {
    id: 103,
    displayOrder: 103,
    difficulty: "easy",
    question: "What has legs but doesn't walk?",
    answer: "A chair",
    hint: "You sit on it.",
  },
  {
    id: 104,
    displayOrder: 104,
    difficulty: "easy",
    question: "What gets sharper the more you use it?",
    answer: "Your brain",
    hint: "Not a physical object.",
  },
  {
    id: 105,
    displayOrder: 105,
    difficulty: "easy",
    question: "What has a bottom at the top?",
    answer: "Your legs",
    hint: "Think about body parts.",
  },
  {
    id: 106,
    displayOrder: 106,
    difficulty: "easy",
    question: "What kind of coat is always wet when you put it on?",
    answer: "A coat of paint",
    hint: "Not clothing.",
  },
  {
    id: 107,
    displayOrder: 107,
    difficulty: "easy",
    question: "What can you break without touching it?",
    answer: "A promise",
    hint: "Not a physical object.",
  },
  {
    id: 108,
    displayOrder: 108,
    difficulty: "easy",
    question: "What goes up when rain comes down?",
    answer: "An umbrella",
    hint: "Protects you from rain.",
  },
  {
    id: 109,
    displayOrder: 109,
    difficulty: "easy",
    question: "What has words but never speaks?",
    answer: "A book",
    hint: "You read it.",
  },
  {
    id: 110,
    displayOrder: 110,
    difficulty: "easy",
    question: "What runs but has no feet?",
    answer: "Water",
    hint: "A liquid.",
  },
  {
    id: 111,
    displayOrder: 111,
    difficulty: "easy",
    question: "What building has the most stories?",
    answer: "A library",
    hint: "Think about books.",
  },
  {
    id: 112,
    displayOrder: 112,
    difficulty: "easy",
    question: "What is always in front of you but can't be seen?",
    answer: "The future",
    hint: "Related to time.",
  },
  {
    id: 113,
    displayOrder: 113,
    difficulty: "easy",
    question: "What month of the year has 28 days?",
    answer: "All of them",
    hint: "Every month has at least 28 days.",
  },
  {
    id: 114,
    displayOrder: 114,
    difficulty: "easy",
    question: "What is at the end of a rainbow?",
    answer: "The letter W",
    hint: "Look at the spelling.",
  },
  {
    id: 115,
    displayOrder: 115,
    difficulty: "easy",
    question: "What can you hold in your left hand but not in your right?",
    answer: "Your right elbow",
    hint: "A body part.",
  },
  {
    id: 116,
    displayOrder: 116,
    difficulty: "easy",
    question: "What goes through cities and fields but never moves?",
    answer: "A road",
    hint: "You drive on it.",
  },
  {
    id: 117,
    displayOrder: 117,
    difficulty: "easy",
    question: "What invention lets you look right through a wall?",
    answer: "A window",
    hint: "Made of glass.",
  },
  {
    id: 118,
    displayOrder: 118,
    difficulty: "easy",
    question: "What is black when clean and white when dirty?",
    answer: "A chalkboard",
    hint: "Used in classrooms.",
  },
  {
    id: 119,
    displayOrder: 119,
    difficulty: "easy",
    question: "What type of cheese is made backwards?",
    answer: "Edam",
    hint: "Spell 'made' backwards.",
  },
  {
    id: 120,
    displayOrder: 120,
    difficulty: "easy",
    question: "What begins and has no end, and ends all things that begin?",
    answer: "Death",
    hint: "The end of life.",
  },
  {
    id: 121,
    displayOrder: 121,
    difficulty: "easy",
    question:
      "What has cities, but no houses; forests, but no trees; and rivers, but no water?",
    answer: "A map",
    hint: "Shows locations.",
  },
  {
    id: 122,
    displayOrder: 122,
    difficulty: "easy",
    question: "What starts with P, ends with E, and has thousands of letters?",
    answer: "Post office",
    hint: "Where mail is handled.",
  },
  {
    id: 123,
    displayOrder: 123,
    difficulty: "easy",
    question: "What has a head and tail but no body?",
    answer: "A coin",
    hint: "Currency.",
  },
  {
    id: 124,
    displayOrder: 124,
    difficulty: "easy",
    question: "What can fill a room but takes up no space?",
    answer: "Light",
    hint: "Opposite of darkness.",
  },
  {
    id: 125,
    displayOrder: 125,
    difficulty: "easy",
    question: "What gets wet while drying?",
    answer: "A towel",
    hint: "Used after bathing.",
  },
  {
    id: 126,
    displayOrder: 126,
    difficulty: "easy",
    question: "What belongs to you but others use it more?",
    answer: "Your name",
    hint: "People call you by it.",
  },
  {
    id: 127,
    displayOrder: 127,
    difficulty: "easy",
    question: "What can jump higher than a building?",
    answer: "Anything, buildings can't jump",
    hint: "Think literally.",
  },
  {
    id: 128,
    displayOrder: 128,
    difficulty: "easy",
    question: "What kind of band never plays music?",
    answer: "A rubber band",
    hint: "Stretchy.",
  },
  {
    id: 129,
    displayOrder: 129,
    difficulty: "easy",
    question: "What type of ship has two mates but no captain?",
    answer: "A relationship",
    hint: "Not a boat.",
  },
  {
    id: 130,
    displayOrder: 130,
    difficulty: "easy",
    question: "What comes down but never goes up?",
    answer: "Rain",
    hint: "Weather related.",
  },
  {
    id: 131,
    displayOrder: 131,
    difficulty: "easy",
    question: "What's full of holes but still holds water?",
    answer: "A sponge",
    hint: "Used for cleaning.",
  },
  {
    id: 132,
    displayOrder: 132,
    difficulty: "easy",
    question: "What room do ghosts avoid?",
    answer: "The living room",
    hint: "Think about the name.",
  },
  {
    id: 133,
    displayOrder: 133,
    difficulty: "easy",
    question: "What has a face and two hands but no arms or legs?",
    answer: "A clock",
    hint: "Tells time.",
  },
  {
    id: 134,
    displayOrder: 134,
    difficulty: "easy",
    question: "What is always coming but never arrives?",
    answer: "Tomorrow",
    hint: "It becomes today.",
  },
  {
    id: 135,
    displayOrder: 135,
    difficulty: "easy",
    question: "What type of dress can never be worn?",
    answer: "An address",
    hint: "Where you live.",
  },
  {
    id: 136,
    displayOrder: 136,
    difficulty: "easy",
    question: "What travels around the world but stays in one corner?",
    answer: "A stamp",
    hint: "On an envelope.",
  },
  {
    id: 137,
    displayOrder: 137,
    difficulty: "easy",
    question: "What has a bank but no money?",
    answer: "A river",
    hint: "A body of water.",
  },
  {
    id: 138,
    displayOrder: 138,
    difficulty: "easy",
    question: "What kind of tree can you carry in your hand?",
    answer: "A palm",
    hint: "Part of your hand.",
  },
  {
    id: 139,
    displayOrder: 139,
    difficulty: "easy",
    question: "What can be cracked, made, told, and played?",
    answer: "A joke",
    hint: "Makes people laugh.",
  },
  {
    id: 140,
    displayOrder: 140,
    difficulty: "easy",
    question: "What loses its head in the morning and gets it back at night?",
    answer: "A pillow",
    hint: "You sleep on it.",
  },

  // MEDIUM RIDDLES (141-200)
  {
    id: 141,
    displayOrder: 141,
    difficulty: "medium",
    question: "I have branches, but no fruit, trunk, or leaves. What am I?",
    answer: "A bank",
    hint: "Financial institution.",
  },
  {
    id: 142,
    displayOrder: 142,
    difficulty: "medium",
    question: "What word has three consecutive double letters?",
    answer: "Bookkeeper",
    hint: "A profession that handles records.",
  },
  {
    id: 143,
    displayOrder: 143,
    difficulty: "medium",
    question:
      "You see a boat filled with people. It has not sunk, but when you look again, you don't see a single person. Why?",
    answer: "All the people were married",
    hint: "Think about the word 'single'.",
  },
  {
    id: 144,
    displayOrder: 144,
    difficulty: "medium",
    question:
      "A doctor gives you three pills and tells you to take one every half hour. How long will they last?",
    answer: "One hour (take one at 0:00, one at 0:30, one at 1:00)",
    hint: "Count the intervals, not the pills.",
  },
  {
    id: 145,
    displayOrder: 145,
    difficulty: "medium",
    question:
      "If you have me, you want to share me. If you share me, you no longer have me. What am I?",
    answer: "A secret",
    hint: "Something confidential.",
  },
  {
    id: 146,
    displayOrder: 146,
    difficulty: "medium",
    question:
      "What English word has three consecutive double letters in a row?",
    answer: "Bookkeeper (or bookkeeping)",
    hint: "Related to accounting.",
  },
  {
    id: 147,
    displayOrder: 147,
    difficulty: "medium",
    question:
      "A rooster lays an egg on top of a barn roof. Which way does it roll?",
    answer: "Roosters don't lay eggs",
    hint: "Think about the bird's gender.",
  },
  {
    id: 148,
    displayOrder: 148,
    difficulty: "medium",
    question: "What disappears as soon as you say its name?",
    answer: "Silence",
    hint: "The absence of sound.",
  },
  {
    id: 149,
    displayOrder: 149,
    difficulty: "medium",
    question:
      "I have seas without water, coasts without sand, towns without people, and mountains without land. What am I?",
    answer: "A map",
    hint: "Shows geography.",
  },
  {
    id: 150,
    displayOrder: 150,
    difficulty: "medium",
    question:
      "What occurs once in a minute, twice in a moment, and never in one thousand years?",
    answer: "The letter M",
    hint: "Look at the spelling.",
  },
  {
    id: 151,
    displayOrder: 151,
    difficulty: "medium",
    question:
      "I am taken from a mine and shut in a wooden case, from which I am never released. What am I?",
    answer: "Pencil lead (graphite)",
    hint: "Used for writing.",
  },
  {
    id: 152,
    displayOrder: 152,
    difficulty: "medium",
    question:
      "What has six faces, but does not wear makeup, has twenty-one eyes, but cannot see?",
    answer: "A die (dice)",
    hint: "Used in games.",
  },
  {
    id: 153,
    displayOrder: 153,
    difficulty: "medium",
    question: "What word becomes shorter when you add two letters to it?",
    answer: "Short (becomes shorter)",
    hint: "Think literally.",
  },
  {
    id: 154,
    displayOrder: 154,
    difficulty: "medium",
    question: "I shave every day, but my beard stays the same. Who am I?",
    answer: "A barber",
    hint: "A profession.",
  },
  {
    id: 155,
    displayOrder: 155,
    difficulty: "medium",
    question: "The more you take away, the larger I become. What am I?",
    answer: "A hole",
    hint: "You dig it.",
  },
  {
    id: 156,
    displayOrder: 156,
    difficulty: "medium",
    question: "What can you catch but never throw?",
    answer: "A cold",
    hint: "An illness.",
  },
  {
    id: 157,
    displayOrder: 157,
    difficulty: "medium",
    question: "What has a tongue but cannot talk, gets around but cannot walk?",
    answer: "A shoe",
    hint: "Footwear.",
  },
  {
    id: 158,
    displayOrder: 158,
    difficulty: "medium",
    question: "What goes up and down stairs without moving?",
    answer: "A carpet or handrail",
    hint: "Part of the staircase.",
  },
  {
    id: 159,
    displayOrder: 159,
    difficulty: "medium",
    question: "What has thirteen hearts but no other organs?",
    answer: "A deck of cards",
    hint: "Used for playing games.",
  },
  {
    id: 160,
    displayOrder: 160,
    difficulty: "medium",
    question:
      "I am always hungry and will die if not fed, but whatever I touch will soon turn red. What am I?",
    answer: "Fire",
    hint: "Hot and dangerous.",
  },
  {
    id: 161,
    displayOrder: 161,
    difficulty: "medium",
    question: "What can travel the entire world while staying in a corner?",
    answer: "A stamp",
    hint: "On mail.",
  },
  {
    id: 162,
    displayOrder: 162,
    difficulty: "medium",
    question:
      "What has roots nobody sees, is taller than trees, up it goes yet it never grows?",
    answer: "A mountain",
    hint: "A landform.",
  },
  {
    id: 163,
    displayOrder: 163,
    difficulty: "medium",
    question: "What kind of room has no windows or doors?",
    answer: "A mushroom",
    hint: "A fungus.",
  },
  {
    id: 164,
    displayOrder: 164,
    difficulty: "medium",
    question: "I make two people out of one. What am I?",
    answer: "A mirror",
    hint: "Shows reflection.",
  },
  {
    id: 165,
    displayOrder: 165,
    difficulty: "medium",
    question: "What breaks yet never falls, and what falls yet never breaks?",
    answer: "Day breaks, night falls",
    hint: "Time of day.",
  },
  {
    id: 166,
    displayOrder: 166,
    difficulty: "medium",
    question:
      "I have cities but no houses, forests but no trees, water but no fish. What am I?",
    answer: "A map",
    hint: "Shows locations.",
  },
  {
    id: 167,
    displayOrder: 167,
    difficulty: "medium",
    question: "What has four wheels and flies?",
    answer: "A garbage truck",
    hint: "Carries waste.",
  },
  {
    id: 168,
    displayOrder: 168,
    difficulty: "medium",
    question: "What gets bigger the more you take away from it?",
    answer: "A hole",
    hint: "You dig it.",
  },
  {
    id: 169,
    displayOrder: 169,
    difficulty: "medium",
    question:
      "I have lakes with no water, mountains with no stone, and cities with no buildings. What am I?",
    answer: "A map",
    hint: "Paper representation.",
  },
  {
    id: 170,
    displayOrder: 170,
    difficulty: "medium",
    question:
      "What can point in every direction but can't reach the destination by itself?",
    answer: "Your finger",
    hint: "Part of your hand.",
  },
  {
    id: 171,
    displayOrder: 171,
    difficulty: "medium",
    question: "I have no life, but I can die. What am I?",
    answer: "A battery",
    hint: "Powers devices.",
  },
  {
    id: 172,
    displayOrder: 172,
    difficulty: "medium",
    question: "What goes up but never comes down?",
    answer: "Your age",
    hint: "Related to time.",
  },
  {
    id: 173,
    displayOrder: 173,
    difficulty: "medium",
    question: "What can you keep after giving it to someone?",
    answer: "Your word",
    hint: "A promise.",
  },
  {
    id: 174,
    displayOrder: 174,
    difficulty: "medium",
    question: "What has a head, a tail, is brown, and has no legs?",
    answer: "A penny",
    hint: "Currency.",
  },
  {
    id: 175,
    displayOrder: 175,
    difficulty: "medium",
    question:
      "What word starts with IS, ends with AND, and has LA in the middle?",
    answer: "Island",
    hint: "Surrounded by water.",
  },
  {
    id: 176,
    displayOrder: 176,
    difficulty: "medium",
    question: "What has one head, one foot, and four legs?",
    answer: "A bed",
    hint: "Furniture.",
  },
  {
    id: 177,
    displayOrder: 177,
    difficulty: "medium",
    question: "What can you serve but never eat?",
    answer: "A tennis ball (or volleyball)",
    hint: "Sports related.",
  },
  {
    id: 178,
    displayOrder: 178,
    difficulty: "medium",
    question: "What runs around a backyard but never moves?",
    answer: "A fence",
    hint: "Marks a boundary.",
  },
  {
    id: 179,
    displayOrder: 179,
    difficulty: "medium",
    question:
      "I am lighter than air but a million men cannot lift me. What am I?",
    answer: "A bubble",
    hint: "It pops easily.",
  },
  {
    id: 180,
    displayOrder: 180,
    difficulty: "medium",
    question: "What has a ring but no finger?",
    answer: "A telephone",
    hint: "Communication device.",
  },
  {
    id: 181,
    displayOrder: 181,
    difficulty: "medium",
    question: "What has one eye but cannot see?",
    answer: "A needle",
    hint: "Used in sewing.",
  },
  {
    id: 182,
    displayOrder: 182,
    difficulty: "medium",
    question: "What has a bottom at its top?",
    answer: "Your legs",
    hint: "Body part.",
  },
  {
    id: 183,
    displayOrder: 183,
    difficulty: "medium",
    question: "What kind of coat can only be put on when wet?",
    answer: "A coat of paint",
    hint: "Not clothing.",
  },
  {
    id: 184,
    displayOrder: 184,
    difficulty: "medium",
    question: "What has many keys but can't open a single lock?",
    answer: "A piano",
    hint: "Musical instrument.",
  },
  {
    id: 185,
    displayOrder: 185,
    difficulty: "medium",
    question: "What has hands but cannot clap?",
    answer: "A clock",
    hint: "Tells time.",
  },
  {
    id: 186,
    displayOrder: 186,
    difficulty: "medium",
    question:
      "What has a bed but never sleeps, can run but never walks, and has a bank but no money?",
    answer: "A river",
    hint: "Body of water.",
  },
  {
    id: 187,
    displayOrder: 187,
    difficulty: "medium",
    question: "What gets broken without being held?",
    answer: "A promise",
    hint: "Not physical.",
  },
  {
    id: 188,
    displayOrder: 188,
    difficulty: "medium",
    question: "What starts with T, ends with T, and has T in it?",
    answer: "A teapot",
    hint: "Used for brewing.",
  },
  {
    id: 189,
    displayOrder: 189,
    difficulty: "medium",
    question:
      "What can be seen in the middle of March and April but can't be seen at the beginning or end of either month?",
    answer: "The letter R",
    hint: "Look at the spelling.",
  },
  {
    id: 190,
    displayOrder: 190,
    difficulty: "medium",
    question: "What has a thumb and four fingers but is not alive?",
    answer: "A glove",
    hint: "Worn on hand.",
  },
  {
    id: 191,
    displayOrder: 191,
    difficulty: "medium",
    question: "What can be right but never wrong?",
    answer: "An angle",
    hint: "Geometry term.",
  },
  {
    id: 192,
    displayOrder: 192,
    difficulty: "medium",
    question: "What belongs to you but is used more by others?",
    answer: "Your name",
    hint: "What people call you.",
  },
  {
    id: 193,
    displayOrder: 193,
    difficulty: "medium",
    question: "What runs but never gets tired?",
    answer: "Water (or a refrigerator)",
    hint: "Can be liquid or appliance.",
  },
  {
    id: 194,
    displayOrder: 194,
    difficulty: "medium",
    question: "What can be measured but has no length, width, or height?",
    answer: "Temperature (or time)",
    hint: "Not a physical dimension.",
  },
  {
    id: 195,
    displayOrder: 195,
    difficulty: "medium",
    question: "What is always in front of you but cannot be seen?",
    answer: "The future",
    hint: "Related to time.",
  },
  {
    id: 196,
    displayOrder: 196,
    difficulty: "medium",
    question: "What has many teeth but cannot bite?",
    answer: "A comb (or saw or zipper)",
    hint: "Used for grooming or cutting.",
  },
  {
    id: 197,
    displayOrder: 197,
    difficulty: "medium",
    question: "What has a foot on each side and one in the middle?",
    answer: "A yardstick",
    hint: "Measuring tool.",
  },
  {
    id: 198,
    displayOrder: 198,
    difficulty: "medium",
    question: "What is black and white and read all over?",
    answer: "A newspaper",
    hint: "Think about the word 'read'.",
  },
  {
    id: 199,
    displayOrder: 199,
    difficulty: "medium",
    question: "What gets answered but never asks a question?",
    answer: "A doorbell or telephone",
    hint: "Makes a sound.",
  },
  {
    id: 200,
    displayOrder: 200,
    difficulty: "medium",
    question: "What has a head and a tail but no body?",
    answer: "A coin",
    hint: "Currency.",
  },

  // HARD RIDDLES (201-240)
  {
    id: 201,
    displayOrder: 201,
    difficulty: "hard",
    question:
      "Three doctors said that Bill was their brother. Bill says he has no brothers. How many brothers does Bill actually have?",
    answer: "None. The doctors are his sisters.",
    hint: "Think about gender assumptions.",
  },
  {
    id: 202,
    displayOrder: 202,
    difficulty: "hard",
    question:
      "I am a word of letters three, add two and fewer there will be. What am I?",
    answer: "Few (add 'er' to make 'fewer')",
    hint: "The word is in the riddle.",
  },
  {
    id: 203,
    displayOrder: 203,
    difficulty: "hard",
    question:
      "What is seen in the middle of March and April that cannot be seen at the beginning or end of either month?",
    answer: "The letter R",
    hint: "Look at the spelling.",
  },
];
